-- RevPay Database Schema for Oracle

-- Users table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone_number VARCHAR2(20) UNIQUE NOT NULL,
    password_hash VARCHAR2(500) NOT NULL,
    transaction_pin VARCHAR2(500) NOT NULL,
    security_question1 VARCHAR2(200),
    security_answer1 VARCHAR2(500),
    security_question2 VARCHAR2(200),
    security_answer2 VARCHAR2(500),
    account_type VARCHAR2(20) CHECK (account_type IN ('PERSONAL', 'BUSINESS')) NOT NULL,
    status VARCHAR2(20) CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    failed_login_attempts NUMBER DEFAULT 0,
    is_locked NUMBER(1) DEFAULT 0,
    business_name VARCHAR2(200),
    business_type VARCHAR2(100),
    tax_id VARCHAR2(50),
    business_address VARCHAR2(500)
);

-- Wallets table
CREATE TABLE wallets (
    wallet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    balance NUMBER(15,2) DEFAULT 0.00,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Payment Methods table
CREATE TABLE payment_methods (
    payment_method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    type VARCHAR2(20) CHECK (type IN ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_ACCOUNT')) NOT NULL,
    encrypted_card_number VARCHAR2(500),
    card_holder_name VARCHAR2(100),
    expiry_month VARCHAR2(2),
    expiry_year VARCHAR2(4),
    encrypted_cvv VARCHAR2(500),
    bank_name VARCHAR2(100),
    account_number VARCHAR2(100),
    routing_number VARCHAR2(20),
    is_default NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Transactions table
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id NUMBER,
    to_user_id NUMBER,
    amount NUMBER(15,2) NOT NULL,
    type VARCHAR2(30) CHECK (type IN ('SEND_MONEY', 'REQUEST_MONEY', 'ADD_MONEY', 'WITHDRAW_MONEY', 
                                     'PAYMENT_RECEIVED', 'INVOICE_PAYMENT', 'LOAN_DISBURSEMENT', 'LOAN_REPAYMENT')) NOT NULL,
    status VARCHAR2(20) CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'DECLINED')) DEFAULT 'PENDING',
    description VARCHAR2(500),
    note VARCHAR2(1000),
    reference_number VARCHAR2(50) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (from_user_id) REFERENCES users(user_id),
    FOREIGN KEY (to_user_id) REFERENCES users(user_id)
);

-- Money Requests table
CREATE TABLE money_requests (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id NUMBER NOT NULL,
    requested_from_id NUMBER NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    description VARCHAR2(500),
    status VARCHAR2(20) CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED')) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    FOREIGN KEY (requester_id) REFERENCES users(user_id),
    FOREIGN KEY (requested_from_id) REFERENCES users(user_id)
);

-- Notifications table
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    type VARCHAR2(30) CHECK (type IN ('TRANSACTION', 'MONEY_REQUEST', 'CARD_CHANGE', 'LOW_BALANCE', 
                                     'INVOICE', 'LOAN_UPDATE', 'SECURITY_ALERT')) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Invoices table (for business accounts)
CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_user_id NUMBER NOT NULL,
    customer_id NUMBER,
    customer_email VARCHAR2(100),
    customer_name VARCHAR2(100),
    invoice_number VARCHAR2(50) UNIQUE NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    description VARCHAR2(1000),
    status VARCHAR2(20) CHECK (status IN ('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED')) DEFAULT 'DRAFT',
    due_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,
    FOREIGN KEY (business_user_id) REFERENCES users(user_id),
    FOREIGN KEY (customer_id) REFERENCES users(user_id)
);

-- Loans table (for business accounts)
CREATE TABLE loans (
    loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_user_id NUMBER NOT NULL,
    loan_amount NUMBER(15,2) NOT NULL,
    purpose VARCHAR2(500),
    status VARCHAR2(20) CHECK (status IN ('APPLIED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'DISBURSED', 'REPAID')) DEFAULT 'APPLIED',
    interest_rate NUMBER(5,2),
    term_months NUMBER,
    monthly_payment NUMBER(15,2),
    outstanding_balance NUMBER(15,2),
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    disbursed_at TIMESTAMP,
    FOREIGN KEY (business_user_id) REFERENCES users(user_id)
);

-- Create indexes for better performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_phone ON users(phone_number);
CREATE INDEX idx_transactions_from_user ON transactions(from_user_id);
CREATE INDEX idx_transactions_to_user ON transactions(to_user_id);
CREATE INDEX idx_transactions_created_at ON transactions(created_at);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_wallets_user_id ON wallets(user_id);
CREATE INDEX idx_payment_methods_user_id ON payment_methods(user_id);

-- Create triggers for wallet creation
CREATE OR REPLACE TRIGGER trg_create_wallet
    AFTER INSERT ON users
    FOR EACH ROW
BEGIN
    INSERT INTO wallets (user_id, balance) VALUES (:NEW.user_id, 0.00);
END;
/

-- Sample data for testing
INSERT INTO users (full_name, email, phone_number, password_hash, transaction_pin, account_type, 
                  security_question1, security_answer1, security_question2, security_answer2) 
VALUES ('John Doe', 'john.doe@email.com', '1234567890', 
        'hashedpassword:salt', 'hashedpin:salt', 'PERSONAL',
        'What is your pet name?', 'hashedanswer1:salt',
        'What is your birth city?', 'hashedanswer2:salt');

INSERT INTO users (full_name, email, phone_number, password_hash, transaction_pin, account_type,
                  business_name, business_type, tax_id, business_address,
                  security_question1, security_answer1, security_question2, security_answer2) 
VALUES ('Jane Smith', 'jane.smith@business.com', '0987654321', 
        'hashedpassword:salt', 'hashedpin:salt', 'BUSINESS',
        'Smith Enterprises', 'Technology', '12-3456789', '123 Business St, City, State',
        'What is your pet name?', 'hashedanswer1:salt',
        'What is your birth city?', 'hashedanswer2:salt');

COMMIT;